apiVersion: v1
kind: Service
metadata:
  name: routing-manager-service
  namespace: kube-system
spec:
  selector:
    component: routing-manager
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090