apiVersion: v1
kind: ServiceAccount
metadata:
  name: latency-meter

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: latency-meter
rules:
  - apiGroups: [""]
    resources: ["pods"]
    verbs: ["get"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: latency-meter
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: latency-meter
subjects:
  - kind: ServiceAccount
    name: latency-meter
