apiVersion: v1
kind: Pod
metadata:
  name: routing-manager # il nome fisso del pod
  namespace: routing  # il namespace in cui il pod viene creato
  labels:
    app: routing-manager
  annotations:
    default-service: "nginx"
    app-name: "nginx"  # la tua nuova annotazione
spec:
  serviceAccountName: routing-manager
  containers:
  - name: routing-manager
    image: crischiaro/routing-manager:latest
    env:
    - name: DEFAULT_SERVICE
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['default-service']
    - name: APP_NAME  # la nuova env variabile
      valueFrom:
        fieldRef:
          fieldPath: metadata.annotations['app-name']
