apiVersion: v1
kind: ServiceAccount
metadata:
  name: routing-manager
  namespace: routing

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole  # o Role se necessario per risorse non a livello di cluster
metadata:
  name: routing-manager
# namespace: default
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch", "update", "delete"]
- apiGroups: ["extensions", "apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update"]

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding  # o RoleBinding se usi Role
metadata:
  name: routing-manager
# namespace: default
subjects:
- kind: ServiceAccount
  name: routing-manager
  namespace: routing  
roleRef:
  kind: ClusterRole  # o Role se necessario
  name: routing-manager
  apiGroup: rbac.authorization.k8s.io
